version: "3"

services:
  server:
    build: server/
    network_mode: host
    ports:
      - 3000:3000

  client:
    build: client/
    network_mode: host
    ports:
      - 4200:4200
    depends_on:
      - server
