name: Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Run client tests
        run: npx ng test

      - name: Upload npm debug log
        uses: actions/upload-artifact@master
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/
