name: Pipeline
on: [push, pull_request]
jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx ng build

  test-client:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install client dependencies
        run: npm ci

      - name: Test
        run: npx ng test
