name: Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Run client tests
        run: npx ng test
